### ISSUE TITLE
Cannot find 'car_keypoints_train.json' file anywhere

### ISSUE THREAD

**Issue by debbypark99** [dineshreddy91/Occlusion_Net#25]
I can't find 'car_keypoints_train.json' file, so my annotations folder is empty now.
Where can I find it?

2021-12-18 04:37:00,304 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.stem.conv1.weight                                          loaded from conv1.weight                 of shape (64, 3, 7, 7)
loading annotations into memory...

Traceback (most recent call last):
  File "train_net.py", line 199, in <module>
    main()
  File "train_net.py", line 192, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "train_net.py", line 76, in train
    start_iter=arguments["iteration"],
  File "/code/lib/data_loader/build.py", line 157, in make_data_loader
    datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)
  File "/code/lib/data_loader/build.py", line 47, in build_dataset
    dataset = factory(**args)
  File "/code/lib/data_loader/datasets/carfusion.py", line 43, in __init__
    super(CARFUSIONDataset, self).__init__(root, ann_file)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torchvision-0.2.2-py3.6.egg/torchvision/datasets/coco.py", line 97, in __init__
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/carfusion/annotations/car_keypoints_train.json'

**Comment by debbypark99** [comment]
Found it out!
